== Unsullied

__highlight your attention__

TIP: If you like Unsullied and want to share the W00t!, I'm grateful for
https://www.gittip.com/bairuidahu/[tips] or
http://of-vim-and-vigor.blogspot.com/[beverages].

=== :Unsullied

The `:Unsullied` command takes an optional number as the 'height' of the
lines above and below the cursor for which to show normal syntax
highlighting. So, for example:

  :Unsullied 5

will show 5 lines above and 5 lines below (both inclusive of the cursor
line) as normally highlighted, while disabling highlighting for all
other lines on the window.

=== Options

Change the following options as desired. The default values for each are as shown.

  let g:unsullied_window_marks = ['t', 'b']
  let g:unsullied_height = 4

=== Bugs

Sometimes Vim doesn't do as it's told and you might occasionally see
stray lines highlighted near the top and bottom edges of the window, or
the whole screen may be highlighted as if Unsullied is not active (like,
after a `zz` cursor-line recentering). The simple solution is to nudge
vim with a line-changing cursor motion, like `jk`. Improvements
tolerated.
